import { createApp } from './app';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import path from 'node:path';
import { carregarAdminToken } from './services/admin.service';
const dir=path.resolve(process.env.DATA_DIR||'.local'); mkdirSync(dir,{recursive:true});
const secretFile=path.join(dir,'jwt.secret');
if(!process.env.JWT_SECRET&&!existsSync(secretFile)) writeFileSync(secretFile,randomBytes(48).toString('hex'),{mode:0o600,flag:'wx'});
const app=createApp(dir,process.env.JWT_SECRET||readFileSync(secretFile,'utf8'),carregarAdminToken(dir));
const port=Number(process.env.PORT||3000), host=process.env.HOST||'127.0.0.1';
app.listen(port,host,()=>console.log(`FácilID: http://${host}:${port} — documentação em /docs`));
